blank_issues_enabled: false
contact_links:
  - name: Embotic Discord Server
    url: https://discord.gg/embotic
  - name: Website
    url: https://embotic.xyz
    about: Our website
  - name: Dashboard
    url: https://dash.embotic.xyz
    about: Embotic dashboard, to create your servers and manage them
  - name: Panel
    url: https://panel.embotic.xyz
    about: Manage your servers with the panel!