name: Egg Request
description: Create an egg request

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING A REQUEST

        **You will be blocked from opening further requests if you don't follow these rules.
        Blatant duplicates will result in a permanent non-appealable ban with no further warning.**
        A blatant duplicate is a duplicate where it's obvious you have put in 0 effort to check
        existing requests (e.g. searching for your own keywords / issue title yields results).
        
        Before opening a request, make sure a similar request doesn't already exist by [searching the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue).
        
        If a similar request already exists, **DO NOT reply** something like "i want this as well". Instead, react with :+1:. Only reply if you want to add additional info.

        Skip formalities like "hello" and do not use AI to "spice up" your request. keep it short and concise with only the information necessary
        ## One Request per issue

        Do not include multiple requests in one issue. If you are making 5 requests, make 5 separate issues
        
        ## Do not request any of the following plugins:
        - Plugins that are not possible:
          - Message search changes (like extra filters)
          - Stereo Mic
          - Nitro features not already provided by [FakeNitro](https://vencord.dev/plugins/FakeNitro) or other existing plugins (e.g. free animated pfp, higher upload limit)
          - Reading private channels
        - Plugins that spam Discord and thus risk an account suspension:
          - Message Pruner
          - Animated Status
          - Nitro Snipers
          - Selfbots
        - Plugins that replace text in your messages, like FxTwitter (use https://vencord.dev/plugins/TextReplace)
        - Plugins that just hide ui elements like the gif button (Use quick css instead) 
        - Plugins that spy on other users (like FakeDeafen)

  - type: textarea
    id: description
    attributes:
      label: Plugin Description
      placeholder: Explain the plugin in detail
    validations:
      required: true

  - type: input
    id: existing-plugin
    attributes:
      label: Existing Plugin for other mod
      description: Does a similar plugin already exist for any other mod? include a link to it
    validations:
      required: false

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      options:
        - label: I read the above and made sure my plugin is possible and allowed
          required: false
        - label: "I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist"
          required: false
        - label: "I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist"
          required: false